---
- hosts:  localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Query contract subjects
      aci_contract_subject:
        hostname: "{{ apic.hostname }}"
        username: "{{ apic.username }}"
        password: "{{ apic.password }}"
        validate_certs: no

        state: query
      register: aci_contract_subject

    - name: Query results
      debug:
        var: aci_contract_subject
