---
- hosts:  localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Setup tenant
      aci_tenant:
        hostname: "{{ apic.hostname }}"
        username: "{{ apic.username }}"
        password: "{{ apic.password }}"
        validate_certs: no

        state: query
      register: tenants

    - name: Tenant setup results
      debug:
        var: tenants
