---
- hosts:  localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Query contract
      aci_contract:
        hostname: "{{ apic.hostname }}"
        username: "{{ apic.username }}"
        password: "{{ apic.password }}"
        validate_certs: no

        state: query
      register: aci_contract

    - name: Query results
      debug:
        var: aci_contract
